# Generated by Django 3.1.11 on 2021-05-21 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('document_type', models.CharField(choices=[('CNPJ', 'CNPJ'), ('CPF', 'CPF'), ('RG', 'RG'), ('Outro', 'Outro')], max_length=5, verbose_name='Document Type')),
                ('document', models.CharField(max_length=50, unique=True, verbose_name='Document')),
                ('job', models.CharField(max_length=50, verbose_name='Job Name')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('comercial', 'Comercial'), ('pessoal', 'Pessoal')], max_length=12, verbose_name='Contact Type')),
                ('number', models.CharField(max_length=12, verbose_name='Contact Type')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.candidate')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
